### ISSUE TITLE
Form Service

### ISSUE THREAD

**Issue by jimxin** [koolkode/bpmn#2]
Hi Martin,

You've done a great job. The famous open source process Engines in Java are being ported to PHP. Thanks for your effort.

It seems lacks for Form Service. And what's your idea for form connection? Thanks.

Best Regards
Jim

**Comment by martinschroeder** [comment]
Hi Jim,

i decided not to implement the form-related features of Activiti because i never used them. Most of the time i needed more control over forms / layouts than auto-generated forms provided. There are no plans to implement such a feature.

I suggest using any kind of web framework (Symfony, Laravel, etc...) to handle the user interaction and forms. Use the TaskService to complete / claim tasks and pass (validated) form data to the complete() method to make it available as process variables.

**Comment by jimxin** [comment]
Yes, it's flexible for forms. Excuse me for my question. What should be used for rendering forms? By any fields on deployment or variables on runtime? Or would you kindly like give me an example? Thanks.

Jim

**Comment by jimxin** [comment]
Thanks for your suggestion.

Jim
