### ISSUE TITLE
Variables from a form

### ISSUE THREAD

**Issue by razvancurcudel** [koolkode/bpmn#5]
Could you provide a small example of using the engine to solve an user task which needs to take some variables from a form to be completed ?

**Comment by martinschroeder** [comment]
Assuming you know the ID (UUID) of the task you want to complete and your validated form data is an associative array named `$vars`:
```php
// Example data, this should be validated from data.
$vars = [
    'product' => 'Some dummy item'
    'quantity' => 4
];

// Find the task to be completed.
$task = $taskService->createTaskQuery()->taskId($uuid)->findOne();

// Complete the task, set 'product' and 'quantity' process variables.
$taskService->complete($task->getId(), $vars);
```
The variables are accessible from `DelegateExecution` in service task implementations and in condition expressions used by BPMN gateways (something like `#{ quantity > 5 }`) or even user task names (`Request for #{ quantity } units of #{ product }`).

**Comment by razvancurcudel** [comment]
Ok. I understood now how to complete a task, but I think i did not understand all the flow.
Let's imagine I have an user task. The user that claimed the task needs to complete a form to take some variables from it. 
Your package only takes these variables and passes them through and doesn't have a way to specify what variables a task has to have in order to be completed. Am I right ? It is my job to see for every task what variables are needed and implement the validation and completeness logic when I receive them, and then to send them to the task service ?

**Comment by martinschroeder** [comment]
Yes, that is how it works. Some process engines (camunda for example) allow you to define form elements in the BPMN file and auto-generate a form from it. I never implemented this because it would not be flexible at all and hard to integrate into applications.

You can use Task::getDefinitionKey() (which is equivalent to the attribute „id“ of the task in your BPMN file) to choose the correct form to use.

For your data objects use eloquent or something to store them in a DB. Avoid storing your data in the process as it is structured storage that can be queried at will. The purpose of the variables passed to complete() is to pass just the few variables that are actually needed by the process itself (to make flow decisions etc.) and nothing else. If you manage orders save them in a DB model (use your framework to do it) and just store the ID of the entity in a process variable. This way you can always load the model from the DB.

**Comment by razvancurcudel** [comment]
Thank you for clarifications! 💯
