### ISSUE TITLE
Nested execution

### ISSUE THREAD

**Issue by razvancurcudel** [koolkode/bpmn#7]
Hello, 

I have a simple BPMN diagram consisting in a start event, 3 user tasks and an end event. When I  start the process instance of that diagram, in the execution table I get 3 rows, which I found that are named nested executions (one being parent of another.) My questions is, what exactly represents these 3 rows ? Why it isn't only one ?

Thanks.

**Comment by martinschroeder** [comment]
Assuming your process starts all 3 usertasks in parallel what happens should be something like this: Starting the process creates 1 root execution (known as a process instance) and an additional execution for each parallel branch of execution (resulting in 3 executions) that holds a reference to the process instance. Executions are somewhat similar to tokens in a Petri Net, they are created (and destroyed) when process execution needs to fork (or join).

**Comment by martinschroeder** [comment]
If the user tasks are placed in sequence their might also be multiple executions depending on usage of things like boundary events or sub-processes. It would be easier to explain it in more depth if you post a picture of your BPMN diagram for reference.

**Comment by razvancurcudel** [comment]
I don't use any boundary event or sub-process. I have a diagram consisting only of 2 user tasks.

![image](https://user-images.githubusercontent.com/9407307/39721060-e3d088e0-5246-11e8-8dac-97b36b5e0fee.png)

When starting a new process instance of this deployment, i get in the execution table 3 executions.

**Comment by martinschroeder** [comment]
You are getting 3 executions due to user tasks being an instance of a "scoped activity". Basically anything that can have boundary events or multi-instance / loop behavior is treated as a scoped activity. This results in the root execution (process instance) being paused, creation of a new execution for the scope (task1) that serves as a common base if there are multiple instances of the task, and finally another execution that executes the user task (task1) as the one-and-only instance.

This is the code that is responsible for the multiple execution instances:
https://github.com/koolkode/bpmn/blob/ba1bb7ad72e1a051ab872207d3efddc2a91a1cfc/src/Engine/AbstractScopeActivity.php#L42-L58
